// Generated by CoffeeScript 1.6.3
(function() {
  var AdventCalendar, app, express, http, mustacheExpress;

  http = require('http');

  express = require('express');

  mustacheExpress = require('mustache-express');

  AdventCalendar = require('./advent_calendar');

  app = express();

  app.set('views', __dirname + '/../views');

  app.engine('mustache', mustacheExpress());

  app.use("/assets", express["static"](__dirname + '/../assets'));

  app.get('/', function(req, res) {
    var calendar;
    calendar = new AdventCalendar();
    return res.render('index.mustache', calendar.calendar_data());
  });

  module.exports = app;

}).call(this);
